version: '3.8'

services:
  database:
    image: postgres:16.3-alpine
    restart: unless-stopped
    ports:
      - "15432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=postgres"
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
